name: Rebuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Helm
        run: |
          curl -sL "https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz" -o helm.tar.gz
          mkdir -p /tmp/helm
          tar -C /tmp/helm -xvf helm.tar.gz
          sudo mv /tmp/helm/linux-amd64/helm /usr/bin/helm

      - name: Repackage charts
        run: helm package src/*

      - name: Rebuild charts index
        run: helm repo index --url https://ccodreanu.github.io/helm-chart/ .

      - name: Update repo with new charts
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.yaml *.tgz
          git commit -m "Rebuild repository"
          git push
